variable "aws_region" {
  type        = string
  default     = "ap-southeast-1"
  description = "AWS region for the Lightsail instance (Singapore, closest to mainland China)."
}

variable "az" {
  type        = string
  default     = "ap-southeast-1a"
  description = "Availability zone for the Lightsail instance."
}

variable "instance_name" {
  type        = string
  default     = "china-proxy"
  description = "Lightsail instance name; also prefixes the key pair and static IP names."
}

variable "bundle_id" {
  type    = string
  # UNVERIFIED 2026-09-26: no AWS credentials on this machine to run
  # `aws lightsail get-bundles`. `tofu plan` will reject an invalid ID;
  # if small_3_0 is absent, pick the cheapest bundle with >= 1 GB RAM.
  default     = "small_3_0"
  description = "Lightsail bundle (size) for the instance."
}

variable "blueprint_id" {
  type    = string
  # UNVERIFIED 2026-09-26: no AWS credentials to run `aws lightsail get-blueprints`.
  # Fallback to ubuntu_22_04 if ubuntu_24_04 is rejected by the API.
  default     = "ubuntu_24_04"
  description = "Lightsail blueprint (OS image) for the instance."
}

variable "domain_name" {
  type        = string
  description = "Your own domain for Hysteria2 ACME http-01, e.g. proxy.example.com. No default."
}

variable "acme_email" {
  type        = string
  description = "Email for ACME (Let's Encrypt) expiry notices. No default."
}

variable "xray_uuid" {
  type        = string
  sensitive   = true
  description = "VLESS client UUID, generated by scripts/generate-secrets.sh. No default."
}

variable "reality_private_key" {
  type        = string
  sensitive   = true
  description = "REALITY private key (x25519), generated by scripts/generate-secrets.sh. No default."
}

variable "reality_short_id" {
  type        = string
  sensitive   = true
  description = "REALITY short ID (8 hex chars), generated by scripts/generate-secrets.sh. No default."
}

variable "hy2_password" {
  type        = string
  sensitive   = true
  description = "Hysteria2 auth password, generated by scripts/generate-secrets.sh. No default."
}

variable "xray_image" {
  type = string
  # Verified 2026-09-26: digest of :26.3.27 equals :latest on ghcr.io;
  # :25.11.09 from the original plan does not exist. Pin exact tag.
  default     = "ghcr.io/xtls/xray-core:26.3.27"
  description = "Prebuilt upstream Xray image (exact tag, never latest)."
}

variable "hy2_image" {
  type = string
  # Verified 2026-09-26: v2.12.3 is the latest stable tag of tobyxdd/hysteria;
  # v2.6.2 from the original plan exists but is outdated. Pin exact tag.
  default     = "tobyxdd/hysteria:v2.12.3"
  description = "Prebuilt upstream Hysteria image (exact tag, never latest)."
}

variable "reality_dest" {
  type        = string
  default     = "www.amazon.com:443"
  description = "REALITY masquerade destination. Never www.microsoft.com (Xray-core handshake exceeds the 8192-byte limit, XTLS/Xray-core#6356)."
}

variable "reality_server_name" {
  type        = string
  default     = "www.amazon.com"
  description = "SNI presented for REALITY; must match reality_dest host."
}

variable "reality_fingerprint" {
  type        = string
  default     = "chrome"
  description = "uTLS fingerprint for REALITY and client configs."
}

variable "ssh_allowed_cidr" {
  type        = string
  default     = "0.0.0.0/0"
  description = "CIDR allowed to reach SSH. Travel IP unknown; open by default."
}
